# This file was generated by GoReleaser. DO NOT EDIT.
cask "muster" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "0cb3bed1142dae3326a0692e3c2a73e94c9b04550daeeefefeb2afb2b9297f67"
      url "https://github.com/filippo-floramo/muster/releases/download/v#{version}/muster_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "273c0b9d054efb0ceb934cd1fcfc4a0772c6cb90e279e28c53c859942311f990"
      url "https://github.com/filippo-floramo/muster/releases/download/v#{version}/muster_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6e30fd83b127eb186eaf872a626d11749ed0f371938ec0c1a29778e04e787de3"
      url "https://github.com/filippo-floramo/muster/releases/download/v#{version}/muster_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "db373438e7e6b58ff5927793eee192c042c57c883e8f275df54163aed21ed237"
      url "https://github.com/filippo-floramo/muster/releases/download/v#{version}/muster_#{version}_linux_amd64.tar.gz"
    end
  end

  name "muster"
  desc "TUI that starts and supervises the dev servers of several repos at once"
  homepage "https://github.com/filippo-floramo/muster"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "muster"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/muster"]
    end
  end

  # No zap stanza required
end
