# This file was generated by GoReleaser. DO NOT EDIT.
cask "muster" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "a5685dab5ebf0a7bc1440098d4686dab5f6570af1ba78eff55388a5475b133e0"
      url "https://github.com/filippo-floramo/muster/releases/download/v#{version}/muster_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1d78094ca2a6c702288a6809e6e592848980c68450d5077f47c83e39764eba41"
      url "https://github.com/filippo-floramo/muster/releases/download/v#{version}/muster_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e434b33aff296228e76918db1ba3eb4b5e8406fa4915c7c16e89ba606012a4d6"
      url "https://github.com/filippo-floramo/muster/releases/download/v#{version}/muster_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "da83e829eccca6becea35bd794c2de3d4b707168cdd039724793e2e2ff0ba0d5"
      url "https://github.com/filippo-floramo/muster/releases/download/v#{version}/muster_#{version}_linux_amd64.tar.gz"
    end
  end

  name "muster"
  desc "TUI that starts and supervises the dev servers of several repos at once"
  homepage "https://github.com/filippo-floramo/muster"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "muster"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/muster"]
    end
  end

  # No zap stanza required
end
