# This file was generated by GoReleaser. DO NOT EDIT.
cask "muster" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "e614a8a84659bc5f03a019d86f4e5a2833c5153956beb989e6559ead4bb41984"
      url "https://github.com/filippo-floramo/muster/releases/download/v#{version}/muster_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5d99140f2594f59a9d2eda75c578690c2d97c730657f9d394dc354bca18338bc"
      url "https://github.com/filippo-floramo/muster/releases/download/v#{version}/muster_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b5aaa853a5841f55fcb2d5450b0092357cf26030869497165f71f6835d1d1787"
      url "https://github.com/filippo-floramo/muster/releases/download/v#{version}/muster_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "acf63208887631ed8c474938acdeb10d606439575a5cb7930b161d160bc02d83"
      url "https://github.com/filippo-floramo/muster/releases/download/v#{version}/muster_#{version}_linux_amd64.tar.gz"
    end
  end

  name "muster"
  desc "TUI that starts and supervises the dev servers of several repos at once"
  homepage "https://github.com/filippo-floramo/muster"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "muster"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/muster"]
    end
  end

  # No zap stanza required
end
